// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6PcQO7p5M2_bWd5QJkTl1kqBVAr9nXg',
    appId: '1:955203154858:web:87685a3286f9dd446471d3',
    messagingSenderId: '955203154858',
    projectId: 'project-b8a71',
    authDomain: 'project-b8a71.firebaseapp.com',
    storageBucket: 'project-b8a71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkpeU5Z0bQLcQvzJc0ez33D9QIe2Brgc',
    appId: '1:955203154858:android:b5bf825743d28d6b6471d3',
    messagingSenderId: '955203154858',
    projectId: 'project-b8a71',
    storageBucket: 'project-b8a71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dQdyqvET21IEuD1PTWcOpDna1Kgl4xs',
    appId: '1:955203154858:ios:f88d92c3154758866471d3',
    messagingSenderId: '955203154858',
    projectId: 'project-b8a71',
    storageBucket: 'project-b8a71.appspot.com',
    androidClientId: '955203154858-iovnuse0uvn2vqlbaes8jtnm7nbf444k.apps.googleusercontent.com',
    iosClientId: '955203154858-djmgmv9mv2n50e19cvhfv07p7bntr4or.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskoopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4dQdyqvET21IEuD1PTWcOpDna1Kgl4xs',
    appId: '1:955203154858:ios:0c451b774a97373c6471d3',
    messagingSenderId: '955203154858',
    projectId: 'project-b8a71',
    storageBucket: 'project-b8a71.appspot.com',
    androidClientId: '955203154858-iovnuse0uvn2vqlbaes8jtnm7nbf444k.apps.googleusercontent.com',
    iosClientId: '955203154858-gna0pvnuthrtch3d2l8uct0djn64090g.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskoopia.RunnerTests',
  );
}
